# Generated by Django 4.0.3 on 2022-03-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_invoice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='token_bling',
            new_name='token',
        ),
    ]
