# Generated by Django 4.0.3 on 2022-03-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_token_bling_configuration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='identifier',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
