# Generated by Django 4.0.3 on 2022-03-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='is_number_store',
        ),
    ]
