# Generated by Django 4.0.3 on 2022-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_configuration_is_number_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('aprovado', 'Aprovado'), ('preparando_envio', 'Preparando Envio'), ('faturado', 'Faturado'), ('pronto_envio', 'Pronto para envio'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
