# Generated by Django 4.0.3 on 2022-03-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
