# Generated by Django 4.0.3 on 2022-03-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expedition_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='group_expedition_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
