# Generated by Django 4.0.3 on 2022-03-11 09:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_expedition_id_order_group_expedition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label',
            field=models.FileField(blank=True, null=True, storage=core.models.OverwriteStorage(), upload_to=''),
        ),
    ]
