# Generated by Django 4.0.3 on 2022-03-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_store',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
