# Generated by Django 4.0.4 on 2022-05-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_configuration_search_labels_order_search_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
