# Generated by Django 4.0.4 on 2022-05-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='status',
            field=models.CharField(blank=True, choices=[('aberto', 'Em aberto'), ('aprovado', 'Aprovado'), ('preparando_envio', 'Preparando Envio'), ('faturado', 'Faturado'), ('pronto_envio', 'Pronto para envio'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], max_length=20, null=True),
        ),
    ]
