# Generated by Django 4.0.4 on 2022-05-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_configuration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='use_invoice_items',
            field=models.BooleanField(default=False),
        ),
    ]
