# Generated by Django 4.0.4 on 2022-12-05 08:53

from django.db import migrations


def set_sent_label_orders(apps, schema_editor):
    Order = apps.get_model('core', 'Order')

    Order.objects.filter(
        search_label=True
    ).update(sent_label=True)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_order_sent_label'),
    ]

    operations = [
        migrations.RunPython(
            set_sent_label_orders,
            reverse_code=migrations.RunPython.noop
        )
    ]
