# Generated by Django 4.0.4 on 2023-01-26 11:20

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=core.fields.CustomCharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=core.fields.CustomCharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='neighbourhood',
            field=core.fields.CustomCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=core.fields.CustomCharField(max_length=2),
        ),
    ]
