# Generated by Django 4.0.4 on 2023-03-21 15:21

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fantasy_name',
            field=core.fields.CustomCharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=core.fields.CustomCharField(blank=True, max_length=60, null=True),
        ),
    ]
